CREATE TABLE ROUTE (
    ID UUID PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    AREA_ID UUID,
    HEIGHT INTEGER,
    NUM_BOLTS INTEGER,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE AREA (
    ID UUID PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

CREATE TABLE CLIMB (
    ID UUID PRIMARY KEY NOT NULL,
    ROUTE_ID UUID,
    BLACK_POINT BOOLEAN,
    RED_POINT BOOLEAN,
    FLASH BOOLEAN,
    ON_SIGHT BOOLEAN,
    NOTES VARCHAR(512),
    SEND_DATE TIMESTAMP,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);