ALTER TABLE CLIMB
RENAME COLUMN SEND_DATE to BLACK_POINT_DATE;

ALTER TABLE CLIMB
ADD COLUMN RED_POINT_DATE TIMESTAMP;

ALTER TABLE CLIMB
ADD COLUMN FLASH_DATE TIMESTAMP;

ALTER TABLE CLIMB
ADD COLUMN ON_SIGHT_DATE TIMESTAMP;